### ISSUE TITLE
`AttributeError: 'tuple' object has no attribute 'type'` when fitting model

### ISSUE THREAD

**Issue by ErikBjare** [braindecode/braindecode#210]
Trying to fit a model in https://github.com/ErikBjare/thesis, but it fails for some unclear reason in `util.py`. Maybe I'm passing the wrong thing somewhere?

I'm using `create_from_X_y` to construct my dataset.

### Notebook

A built notebook with the failing code is available at: https://erik.bjareholt.com/thesis/Main.html 

The error is at the bottom, you can Ctrl+F for 'Braindecode' to get to the right section.

### Traceback

```
Traceback (most recent call last):
  File "<ipython-input-20-cc32874bace5>", line 34, in <module>
    clf.fit(train_set, y=None, epochs=n_epochs)
  File "/home/erb/.virtualenvs/erb-thesis/lib/python3.8/site-packages/skorch/classifier.py", line 142, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "/home/erb/.virtualenvs/erb-thesis/lib/python3.8/site-packages/skorch/net.py", line 917, in fit
    self.partial_fit(X, y, **fit_params)
  File "/home/erb/.virtualenvs/erb-thesis/lib/python3.8/site-packages/skorch/net.py", line 876, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/home/erb/.virtualenvs/erb-thesis/lib/python3.8/site-packages/skorch/net.py", line 789, in fit_loop
    self.run_single_epoch(dataset_train, training=True, prefix="train",
  File "/home/erb/.virtualenvs/erb-thesis/lib/python3.8/site-packages/skorch/net.py", line 822, in run_single_epoch
    for data in self.get_iterator(dataset, training=training):
  File "/home/erb/.virtualenvs/erb-thesis/lib/python3.8/site-packages/braindecode/util.py", line 323, in __iter__
    y = y.type(torch.int64)
AttributeError: 'tuple' object has no attribute 'type'
```

I assume it expects `y` to be a tensor here, but it seems like it isn't. Perhaps a similar check should exist for `y` as for `x` (`hasattr('type')`).

Tested both in latest PyPI release and on latest git master, same result.

**Comment by robintibor** [comment]
ya it probably could be improved in any case. but to solve your problem, why did you disable
```
#y = np.array([0 if yy == 'prose' else 1 for yy in y])
``` 
? It seesm right now y is an array of strings? we should work towards that this also works, but atm I think it will only work if y is a list/np-array of integers or sth

**Comment by ErikBjare** [comment]
That was indeed the issue, thanks!

If you aim to be compatible with sklearn might be worth supporting it, or just add a better error message. No biggie anyway, hopefully the next person to make this mistake will find this issue when searching :)

Closing.
