### ISSUE TITLE
`preprocess` fails for `n_jobs`>1

### ISSUE THREAD

**Issue by dcwil** [braindecode/braindecode#325]
Running the latest master I run into issues with the parallelised preprocessing:

```
from braindecode.preprocessing import Preprocessor, preprocess, filterbank
from braindecode.datasets.moabb import MOABBDataset

ds = MOABBDataset(dataset_name='Schirrmeister2017',
                           subject_ids=[1], )
splits = ds.split([[i] for i in range(len(ds.datasets))])

fbank = [
            Preprocessor(
                apply_on_array=False,
                fn=filterbank,
                frequency_bands=[(0, 10)],
                verbose=False,
                n_jobs=1
            ),
        ]

for split_i, split_ds in splits.items():
    preprocess(concat_ds=split_ds, preprocessors=fbank, n_jobs=2)
```
gives the following output:

```
Creating RawArray with float64 data, n_channels=128, n_times=1225545
    Range : 0 ... 1225544 =      0.000 ...  2451.088 secs
Ready.
Creating RawArray with float64 data, n_channels=128, n_times=616535
    Range : 0 ... 616534 =      0.000 ...  1233.068 secs
Ready.
320 events found
Event IDs: [1 2 3 4]
160 events found
Event IDs: [1 2 3 4]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/braindecode/preprocessing/preprocess.py", line 223, in _preprocess
    _preprocess_raw_or_epochs(ds.raw, preprocessors)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/braindecode/preprocessing/preprocess.py", line 220, in _preprocess_raw_or_epochs
    preproc.apply(raw_or_epochs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/braindecode/preprocessing/preprocess.py", line 62, in apply
    self._try_apply(raw_or_epochs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/braindecode/preprocessing/preprocess.py", line 74, in _try_apply
    self.fn(raw_or_epochs, **self.kwargs)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/braindecode/preprocessing/preprocess.py", line 473, in filterbank
    raw.add_channels(all_filtered)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/mne/channels/channels.py", line 1051, in add_channels
    self._data.base.resize(n_bytes)
TypeError: mmap can't resize a readonly or copy-on-write memory map.
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-afd28816663e>", line 19, in <module>
    preprocess(concat_ds=split_ds, preprocessors=fbank, n_jobs=2)
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/braindecode/preprocessing/preprocess.py", line 158, in preprocess
    list_of_ds = Parallel(n_jobs=n_jobs)(
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/dan/Documents/AGBALL/RiemNetEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
TypeError: mmap can't resize a readonly or copy-on-write memory map.
```

**Comment by agramfort** [comment]
I don't replicate the pb on my mac using latest version of braindecode on master branch.

**Comment by dcwil** [comment]
Strange - I just uninstalled and then reinstalled with:
`pip install https://github.com/braindecode/braindecode/archive/master.zip`

and still run into the same issue (joblib=1.0.1, mne=0.23.0)

**Comment by agramfort** [comment]
can you also update mne to main branch?

>

**Comment by dcwil** [comment]
Same issue running mne=0.24.dev0

**Comment by hubertjb** [comment]
I was just able to reproduce the issue on a server, I'll look into it @dcwil

**Comment by hubertjb** [comment]
Seems like the issue is with joblib.Parallel's `max_nbytes` argument, which is set to 1 MB by default. The code fails because the data that has to be memmapped is around 1.3 GB in the case of this dataset. For instance, this didn't fail when I cropped the data and picked only a few channels.

I'm not sure what the best approach would be to fix this issue in the codebase. It would be nice to be able to set `max_nbytes` with the standard joblib context manager, that way users could adapt this based on the size of their data - there is an open issue here on this, not sure whether this will be addressed at some point: https://github.com/joblib/joblib/issues/912

Another option would be to add a `max_nbytes` parameter to `preprocess()`.

Any ideas/preferences @agramfort @robintibor ?

**Comment by hubertjb** [comment]
I spent a bit more time looking into this, and I think I was actually looking at the problem the wrong way. The error occurs because of two things: (1) the data is preloaded (this dataset is loaded from .mat files so it cannot be created with preload=False), and (2) `preprocess.filterbank()` resizes the internal data when concatenating all the filtered channels together. 

When the data is preloaded and the data is above joblib's default max_nbytes=1 MB, the data is automatically memapped. Memapped arrays cannot be resized, which raises the error reported above. If on the other hand the dataset had been created with preload=False there would be no memapping and no error (the `Preprocessor` would call `load_data` inside each process). 

**Possible solutions:** 
(1) work with preload=False. A hack when the data is e.g. in .mat format would be to save the BaseConcatDataset and reload it with `preload=False`.
(2) Provide a `max_nbytes` argument in `preprocess` and ask the user to disable memapping whenever a preprocessing function reshapes the array/raises this error.
(3) Disable memapping altogether by setting `max_nbytes=None` in `preprocess`.

I think (1) is not efficient or elegant. (3) would mean we never benefit from joblib's memapping capabilities, and so lose out on the chance to further reduce memory usage. I think (2) is our best shot.

**Here's what I suggest:**
- Adding a `max_nbytes` argument to `preprocess`.
- Catching the error reported by @dcwil inside `preprocess` and raising our own error that clearly indicates what the problem is and how to fix it (i.e., by setting `max_nbyes=None` or using preload=False)

If @agramfort and @gemeinl agree with the solution I'll do a quick PR to fix this.

**Comment by agramfort** [comment]
fine with me

>

**Comment by bruAristimunha** [comment]
Hello @dcwil,

I was wondering, can we close this issue?

**Comment by dcwil** [comment]
Hi @bruAristimunha

Looks like I can still reproduce the error in 0.6, using the same snippet
