### ISSUE TITLE
TypeError: on_batch_end() missing 2 required positional arguments: 'X' and 'y'

### ISSUE THREAD

**Issue by whiteram** [braindecode/braindecode#362]
I run `plot_bcic_iv_2a_moabb_trial.py` from https://braindecode.org/auto_examples/plot_bcic_iv_2a_moabb_trial.html in my vscode, but end with this error.
```
Loading data for 48 events and 1125 original time points ...
0 bad epochs dropped
Traceback (most recent call last):
  File "d:/whiteram/Documents/PythonScripts/BCI/plot_bcic_iv_2a_moabb_trial.py", line 233, in <module>
    clf.fit(train_set, y=None, epochs=n_epochs)
  File "D:\Software\Devel\Anaconda3\envs\snake1v1\lib\site-packages\skorch\classifier.py", line 141, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
  File "D:\Software\Devel\Anaconda3\envs\snake1v1\lib\site-packages\skorch\net.py", line 1215, in fit
    self.partial_fit(X, y, **fit_params)
  File "D:\Software\Devel\Anaconda3\envs\snake1v1\lib\site-packages\skorch\net.py", line 1174, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "D:\Software\Devel\Anaconda3\envs\snake1v1\lib\site-packages\skorch\net.py", line 1088, in fit_loop
    step_fn=self.train_step, **fit_params)
  File "D:\Software\Devel\Anaconda3\envs\snake1v1\lib\site-packages\skorch\net.py", line 1127, in run_single_epoch
    self.notify("on_batch_end", batch=batch, training=training, **step)
  File "D:\Software\Devel\Anaconda3\envs\snake1v1\lib\site-packages\skorch\net.py", line 357, in notify
    getattr(self, method_name)(self, **cb_kwargs)
TypeError: on_batch_end() missing 2 required positional arguments: 'X' and 'y'
```

**Comment by robintibor** [comment]
Are you on newest braindecode from github? maybe that could solve it already

**Comment by rycamargo** [comment]
I was getting the same error with version 0.5.1. 

Installing the newest version from GitHub solved the problem.

**Comment by kje1439** [comment]
Is their any newest version other than 0.5.1?

**Comment by robintibor** [comment]
Now there is 0.6, problem should be fixed, please reopen if the issue persists
