### ISSUE TITLE
Incompatible with MNE 1.0.2:  cannot import name '_fetch_file' from 'mne.utils' 

### ISSUE THREAD

**Issue by TheAutumnOfRice** [braindecode/braindecode#383]
braindecode version: 0.6
mne version: 1.0.2

Input code:
```python
from braindecode.datasets.bbci import BBCIDataset
```

Output:
```
Traceback (most recent call last):
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8d9acc991253>", line 1, in <module>
    from braindecode.datasets.bbci import BBCIDataset
  File "C:\Program Files\JetBrains\PyCharm 2020.3.5\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\braindecode\datasets\__init__.py", line 5, in <module>
    from .moabb import MOABBDataset, HGD, BNCI2014001
  File "C:\Program Files\JetBrains\PyCharm 2020.3.5\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\braindecode\datasets\moabb.py", line 114, in <module>
    class BNCI2014001(MOABBDataset):
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\braindecode\datasets\moabb.py", line 124, in BNCI2014001
    from moabb.datasets import BNCI2014001
  File "C:\Program Files\JetBrains\PyCharm 2020.3.5\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\moabb\datasets\__init__.py", line 8, in <module>
    from .alex_mi import AlexMI
  File "C:\Program Files\JetBrains\PyCharm 2020.3.5\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\moabb\datasets\alex_mi.py", line 7, in <module>
    from . import download as dl
  File "C:\Program Files\JetBrains\PyCharm 2020.3.5\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\moabb\datasets\download.py", line 12, in <module>
    from mne.utils import _fetch_file, _url_to_local_path, verbose
ImportError: cannot import name '_fetch_file' from 'mne.utils' (C:\Users\Autumnii\.conda\envs\torch\lib\site-packages\mne\utils\__init__.py)
```

However, when I was using mne=0.23, there would be no error.
I'm using python3.7 with win10.

**Comment by TheAutumnOfRice** [comment]
I just noticed that this issue should be the problem of moabb.
