### ISSUE TITLE
USleep TypeError when printing modules

### ISSUE THREAD

**Issue by brunaafl** [braindecode/braindecode#537]
`
m = USleep()
for name, module in m.named_modules():
    print(name)
    print(module)
`
is returning the following error:
`TypeError: kernel_size has an unexpected type: <class 'numpy.int64'>`

More specifically:
`
Traceback (most recent call last):
  File "/home/brunalopes/PycharmProjects/braindecode/eeg/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-c1a9f6a7a3e7>", line 5, in <module>
    print(module)
  File "/home/brunalopes/PycharmProjects/braindecode/braindecode/models/base.py", line 291, in __str__
    return str(self.get_torchinfo_statistics())
  File "/home/brunalopes/PycharmProjects/braindecode/braindecode/models/base.py", line 282, in get_torchinfo_statistics
    return summary(
  File "/home/brunalopes/PycharmProjects/braindecode/eeg/lib/python3.10/site-packages/torchinfo/torchinfo.py", line 223, in summary
    summary_list = forward_pass(
  File "/home/brunalopes/PycharmProjects/braindecode/eeg/lib/python3.10/site-packages/torchinfo/torchinfo.py", line 275, in forward_pass
    summary_list, _, hooks = apply_hooks(model_name, model, x, batch_dim)
  File "/home/brunalopes/PycharmProjects/braindecode/eeg/lib/python3.10/site-packages/torchinfo/torchinfo.py", line 634, in apply_hooks
    global_layer_info[module_id] = LayerInfo(
  File "/home/brunalopes/PycharmProjects/braindecode/eeg/lib/python3.10/site-packages/torchinfo/layer_info.py", line 59, in __init__
    self.kernel_size = self.get_kernel_size(module)
  File "/home/brunalopes/PycharmProjects/braindecode/eeg/lib/python3.10/site-packages/torchinfo/layer_info.py", line 168, in get_kernel_size
    raise TypeError(f"kernel_size has an unexpected type: {type(k)}")
TypeError: kernel_size has an unexpected type: <class 'numpy.int64'>
`

**Comment by sliwy** [comment]
Looks like something for me, I'm gonna see why it's not working
